let foods=[];let state=JSON.parse(localStorage.getItem('calfuel-state')||'{}');
state.goals={calories:2200,protein:160,carbs:240,fat:70,...(state.goals||{})};state.log||=[];state.mixIds||=[];
const $=id=>document.getElementById(id),keys=['calories','protein','carbs','fat'],safe=v=>Number(v)||0,persist=()=>localStorage.setItem('calfuel-state',JSON.stringify(state));
const category=f=>{const n=f.name.toLowerCase();if(/cookie|cake|dessert|soft serve|ice cream|pudding|brownie/.test(n))return'dessert';if(/chicken|beef|salmon|turkey|tuna|tofu|bean|lentil|dal|egg|yogurt|brisket/.test(n))return'protein';if(/rice|pasta|noodle|potato|bread|waffle|bagel|roll|oatmeal|fries|samosa/.test(n))return'carb';return'vegetable'};
const grams=f=>({protein:120,carb:160,vegetable:100,dessert:85}[category(f)]||120);
const totals=()=>state.log.reduce((a,id)=>{const f=foods.find(x=>x.id===id);if(f)keys.forEach(k=>a[k]+=safe(f[k]));return a},{calories:0,protein:0,carbs:0,fat:0});
function renderDashboard(){const t=totals(),g=state.goals,p=Math.min(100,Math.round(t.calories/g.calories*100));$('caloriesTotal').textContent=t.calories;$('calorieGoalLabel').textContent=g.calories;$('calorieRing').style.background=`conic-gradient(var(--orange) ${p*3.6}deg,#e9eee6 0deg)`;$('statusLine').textContent=t.calories?`${Math.max(g.calories-t.calories,0)} kcal left today.`:'Start building your day.';$('macroGrid').innerHTML=[['Protein','protein'],['Carbs','carbs'],['Fat','fat']].map(([l,k])=>`<div class="macro"><b>${t[k]}<small>g</small></b><span>${l} · ${g[k]}g goal</span></div>`).join('')}
function renderFoods(){const term=$('search').value.toLowerCase(),meal=$('mealFilter').value,filter=$('categoryFilter').value;$('foods').innerHTML=foods.filter(f=>(meal==='all'||f.meal===meal)&&(filter==='all'||category(f)===filter)&&f.name.toLowerCase().includes(term)).map(f=>`<article class="food-card"><span class="station">${f.meal} · <b>${category(f)}</b></span><h3>${f.name}</h3><p class="numbers">${f.calories} kcal · P ${f.protein}g · C ${f.carbs}g · F ${f.fat}g</p><p class="muted">Est. ${grams(f)}g per serving</p><button class="use ${state.mixIds.includes(f.id)?'selected':''}" data-use="${f.id}">${state.mixIds.includes(f.id)?'Selected for split':'Use in plan'}</button><button class="add" data-add="${f.id}">Add to log</button></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{state.log.push(b.dataset.add);persist();renderDashboard()});document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const id=b.dataset.use;state.mixIds=state.mixIds.includes(id)?state.mixIds.filter(x=>x!==id):[...state.mixIds,id];persist();renderFoods();renderMixer()})}
function bestFor(type){const set=foods.filter(f=>category(f)===type);const score={protein:f=>safe(f.protein)/Math.max(1,safe(f.calories)),carb:f=>safe(f.carbs)/Math.max(1,safe(f.calories)),vegetable:f=>safe(f.protein)+safe(f.carbs)/4}[type];return [...set].sort((a,b)=>score(b)-score(a))[0]||foods[0]}
function schedule(){const enabled=[...document.querySelectorAll('[data-meal]:checked')].map(x=>x.dataset.meal),shares=Object.fromEntries([...document.querySelectorAll('[data-share]')].map(x=>[x.dataset.share,safe(x.value)]));const sum=enabled.reduce((a,m)=>a+shares[m],0);return{enabled,shares,sum}}
function generatePlan(){const s=schedule();if(!s.enabled.length||s.sum!==100){$('plan').className='plan empty';$('plan').textContent=`Choose at least one meal and make enabled meal percentages add to 100% (currently ${s.sum}%).`;return}const p=bestFor('protein'),c=bestFor('carb'),v=bestFor('vegetable'),g=state.goals;let all={calories:0,protein:0,carbs:0,fat:0};const cards=s.enabled.map(meal=>{const share=s.shares[meal]/100,ps=g.protein*share/Math.max(1,p.protein),cs=g.carbs*share/Math.max(1,c.carbs),vs=.75;const rows=[[p,ps],[c,cs],[v,vs]];const t=rows.reduce((a,[f,n])=>{keys.forEach(k=>a[k]+=safe(f[k])*n);return a},{calories:0,protein:0,carbs:0,fat:0});keys.forEach(k=>all[k]+=t[k]);return `<article class="meal-card"><p class="eyebrow">${meal.toUpperCase()} · ${s.shares[meal]}%</p><h3>${Math.round(t.calories)} kcal plate</h3>${rows.map(([f,n])=>`<div class="meal-item"><span><b>${f.name}</b><small>${n.toFixed(2)} servings · <strong>${Math.round(n*grams(f))}g</strong></small></span><span>${Math.round(safe(f.calories)*n)} kcal</span></div>`).join('')}<p class="numbers">P ${Math.round(t.protein)}g · C ${Math.round(t.carbs)}g · F ${Math.round(t.fat)}g</p></article>`}).join('');$('plan').className='plan';$('plan').innerHTML=cards+`<article class="meal-card"><p class="eyebrow">DAY ESTIMATE</p><h3>${Math.round(all.calories)} kcal</h3><p class="numbers">P ${Math.round(all.protein)}g · C ${Math.round(all.carbs)}g · F ${Math.round(all.fat)}g</p><p class="muted">Weights are serving estimates. Use a scale or dining-hall serving utensils when possible.</p></article>`}
function renderMixer(){const selected=state.mixIds.map(id=>foods.find(f=>f.id===id)).filter(Boolean),macro=$('mixMacro').value;$('mixUnit').textContent=macro==='calories'?'kcal':'g';$('mixChoices').innerHTML=selected.length?selected.map(f=>`<label class="portion-row"><span><b>${f.name}</b><small>${f[macro]}${macro==='calories'?' kcal':'g'} / ${grams(f)}g serving</small></span><input class="share" data-id="${f.id}" type="number" value="${Math.floor(100/selected.length)}" min="0" max="100"/><em>%</em></label>`).join(''):'<p class="muted">Select foods using “Use in plan.”</p>';$('mixResult').innerHTML=''}
function calculateMix(){const macro=$('mixMacro').value,target=safe($('mixTarget').value),shares=[...document.querySelectorAll('.share')].map(x=>({id:x.dataset.id,value:safe(x.value)})),sum=shares.reduce((a,x)=>a+x.value,0);if(!shares.length){$('mixResult').innerHTML='<p class="warning">Select foods first.</p>';return}if(sum!==100){$('mixResult').innerHTML=`<p class="warning">Percentages total ${sum}%. They must total 100%.</p>`;return}$('mixResult').innerHTML=`<p class="eyebrow">YOUR SPLIT</p>`+shares.map(({id,value})=>{const f=foods.find(x=>x.id===id),amount=target*value/100,servings=amount/Math.max(1,safe(f[macro]));return `<div class="portion-result"><b>${f.name}</b><span>${value}% → <strong>${Math.round(servings*grams(f))}g</strong> (${servings.toFixed(2)} servings)</span></div>`}).join('')}
async function init(){const menu=window.CALFUEL_MENU||await fetch('data/cafe3-menu.json').then(r=>r.json());foods=menu.items.filter(f=>keys.every(k=>Number.isFinite(Number(f[k]))));$('menuInfo').textContent=`Café 3 snapshot · ${new Date(menu.refreshedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · estimates shown`;const inputs={calories:'calorieGoal',protein:'proteinGoal',carbs:'carbGoal',fat:'fatGoal'};Object.entries(inputs).forEach(([k,id])=>$(id).value=safe(state.goals[k]));$('saveGoals').onclick=()=>{Object.entries(inputs).forEach(([k,id])=>state.goals[k]=safe($(id).value));persist();renderDashboard();generatePlan()};$('generatePlan').onclick=generatePlan;$('search').oninput=renderFoods;$('mealFilter').onchange=renderFoods;$('categoryFilter').onchange=renderFoods;$('mixMacro').onchange=renderMixer;$('calculateMix').onclick=calculateMix;renderDashboard();renderFoods();renderMixer();generatePlan()}
init().catch(e=>$('menuInfo').textContent=`Could not load the menu: ${e.message}`);
